### ISSUE TITLE
Request: Resize YT To Window Size and Resize Video To Window Size

### ISSUE THREAD

**Issue by Dyras** [FiorenMas/Userscripts#1]
Hello! Any chance you could add support for these two:

https://greasyfork.org/en/scripts/811-resize-yt-to-window-size
https://greasyfork.org/en/scripts/10815-resize-video-to-window-size

Thanks in advance!

**Comment by FiorenMas** [comment]
> Hello! Any chance you could add support for these two:
> 
> https://greasyfork.org/en/scripts/811-resize-yt-to-window-size https://greasyfork.org/en/scripts/10815-resize-video-to-window-size
> 
> Thanks in advance!

Thanks for the suggestion! I've added it. You can check it on the Downloads page (use Ctrl+F to search for "Resize YT To Window Size" or "Resize Video To Window Size").
