### ISSUE TITLE
Replace Bing Increase Word Limit with something else

### ISSUE THREAD

**Issue by Dyras** [FiorenMas/Userscripts#2]
Hello! It seems this script:

https://greasyfork.org/en/scripts/483319-bing-increase-word-limit
Has been deleted:

> The script you requested has been deleted, but here are some related scripts.

That's never a good sign. Maybe you should replace it with something similar?

This one seems identical + it prevents the scrolling annoyance:
https://greasyfork.org/en/scripts/464747-enhanced-bing-chatai

**Comment by FiorenMas** [comment]
Thank you for suggestion!
https://github.com/FiorenMas/Userscripts/commit/70c83b9dcd504e4e8bf7cc0c843546bf7f0527e2
